# -*- coding: utf-8 -*-
"""image seg1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqnRjQmm5HQIqolxkhPrE7BpcRygbIhK
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import cv2

image = mpl.image.imread("/content/sunset-1373171_1280.jpg")
plt.imshow(image)

image.shape

x = image.reshape(-1, 3)
x.shape

kmeans = KMeans(n_clusters=3, n_init= 10)

kmeans.fit(x)

seg_image = kmeans.cluster_centers_[kmeans.labels_]
seg_image = seg_image.reshape(image.shape)
plt.imshow(seg_image/255)

cv2.imwrite("/content/sunset-1373171_1280.jpg", cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
cv2.imwrite("/content/sunset-1373171_1280.jpg", cv2.cvtColor(seg_image.astype("uint8"), cv2.COLOR_BGR2RGB))